### ISSUE TITLE
Installation from source successful, runtime unsuccessful

### ISSUE THREAD

**Issue by danionescu2007** [talkkonnect/talkkonnect#61]
Trying to install from source. Followed the guide here https://github.com/talkkonnect/talkkonnect/blob/main/README.md#installation-instructions-for-raspberry-pi-boards-from-source-code on a RPI 4B

When running the binary I get at runtime:
```
talkkonnect@rpi1:~/bin $ ./talkkonnect 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/talkkonnect/talkkonnect.(*Talkkonnect).ClientStart(0x1b30000)
	/home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/client.go:539 +0x28fc
github.com/talkkonnect/talkkonnect.Init({0x63a75c, 0x4f}, {0x608902, 0x1})
	/home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/client.go:237 +0x134c
main.main()
	/home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/cmd/talkkonnect/main.go:78 +0x3bc
```
Here is attached the xml configuration that I am trying to use:
[talkkonnect.xml.txt](https://github.com/talkkonnect/talkkonnect/files/8492456/talkkonnect.xml.txt)

Any help is truly appreciated.

**Comment by danionescu2007** [comment]
I guess I am really tired. I used 1.x version of config template against the 2.x version of code. My bad.
Over and out  :)
