### ISSUE TITLE
TalkKonnect Client connects to server but then immediately leaves again

### ISSUE THREAD

**Issue by OverlayFox** [talkkonnect/talkkonnect#66]
I'm currently trying to make TalkKonnect run in a very simple config where you essentially just run it as a walky-talky on a Raspberry Pi 3B+
But I'm having issues keeping the TalkKonnect Client connected to the Server.
When I start the TalkKonnect Binary it connects to the server for a brief second, is logged by the server as successfully connected, but then the client immediately leaves again

The Log file sadly does not get written to and remains empty no matter what I state in the XML config file
And the screen output doesn't show any errors, only that it has connected successfully and the welcome message of the server
But immediately crashes afterwards with no hint as to why

The only thing I'm getting is this from the Terminal:

`panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/talkkonnect/talkkonnect.(*Talkkonnect).ClientStart(0x2f12000)
        /home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/client.go:539 +0x2c54
github.com/talkkonnect/talkkonnect.Init({0x6a8f14, 0x4f}, {0x675af9, 0x1})
        /home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/client.go:237 +0x13c0
main.main()
        /home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/cmd/talkkonnect/main.go:78 +0x3bc`

It would be amazing if someone could help find the issue in this
I myself am not versed in Go and only in python and C++ so this is new territory for me ^^'

**Comment by OverlayFox** [comment]
Welp....I was stupid and didn't see the runtime error x3
You just have to use the version2 config and not the version1 as stated in another issue that was already resolved x3
